services:
  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      
  front-end:
    build: https://github.com/twatch-project/twatch-project.git#develop
    volumes:
      - ./src:/app/src
    ports:
      - 5173:5173