services:
  pg:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "academy"

  rd:
    image: redis:latest

  app-backend:
    # Build image nodeserver from Dockerfile in GitHub repo
    image: genochs/carftcon-backend
    environment:
      POSTGRES_PASSWORD: "academy"
      REDIS_URL: "redis://rd:6379"
      DATABASE_URL: "postgresql://pguser:academy@pg:5432"
    ports:
      - "8000:8000"

  app-frontend:
    image: genochs/carftcon-frondend
    ports:
      - "80:80"
