name: Test workflows
run-name: "[${{ github.sha }}] Triggering test by ${{ github.actor }}"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test TypeScript code for event ${{ github.event_name }} on ${{ github.ref }}
    strategy:
      matrix:
        nodeversion: [">=18.x", latest]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking out ${{ github.ref }} ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.nodeversion }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Setup pnpm@latest with Node.js ${{ matrix.nodeversion }} on ${{ matrix.os }}
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Installing dependencies with `pnpm install`
        run: pnpm install
      # - name: Running Jest tests with Node.js ${{ matrix.nodeversion }} on ${{ matrix.os }}
      #   run: pnpm test
